In [1]:
import pandas as pd
chartevents = pd.read_csv('chartevents.csv')
chartevents.head()

,subject_id,hadm_id,stay_id,caregiver_id,charttime,storetime,itemid,value,valuenum,valueuom,warning
0,10005817,20626031,32604416,6770.0,2132-12-16 00:00:00,2132-12-15 23:45:00,225054,On,NaN,NaN,0.0
1,10005817,20626031,32604416,6770.0,2132-12-16 00:00:00,2132-12-15 23:43:00,223769,100,100.0,%,0.0
2,10005817,20626031,32604416,6770.0,2132-12-16 00:00:00,2132-12-15 23:47:00,223956,Atrial demand,NaN,NaN,0.0
3,10005817,20626031,32604416,6770.0,2132-12-16 00:00:00,2132-12-15 23:47:00,224866,Yes,NaN,NaN,0.0
4,10005817,20626031,32604416,6770.0,2132-12-16 00:00:00,2132-12-15 23:45:00,227341,No,0.0,NaN,0.0

In [2]:
labevents = pd.read_csv('labevents.csv')
labevents.head()

,labevent_id,subject_id,hadm_id,specimen_id,itemid,order_provider_id,charttime,storetime,value,valuenum,valueuom,ref_range_lower,ref_range_upper,flag,priority,comments
0,172061,10014354,29600294.0,1808066,51277,NaN,2148-08-16 00:00:00,2148-08-16 01:30:00,15.4,15.40,%,10.5,15.5,NaN,ROUTINE,NaN
1,172062,10014354,29600294.0,1808066,51279,NaN,2148-08-16 00:00:00,2148-08-16 01:30:00,3.35,3.35,m/uL,4.6,6.1,abnormal,ROUTINE,NaN
2,172068,10014354,29600294.0,1808066,52172,NaN,2148-08-16 00:00:00,2148-08-16 01:30:00,49.7,49.70,fL,35.1,46.3,abnormal,ROUTINE,NaN
3,172063,10014354,29600294.0,1808066,51301,NaN,2148-08-16 00:00:00,2148-08-16 01:30:00,20.3,20.30,K/uL,4.0,10.0,abnormal,ROUTINE,NaN
4,172050,10014354,29600294.0,1808066,51249,NaN,2148-08-16 00:00:00,2148-08-16 01:30:00,31.1,31.10,g/dL,32.0,37.0,abnormal,ROUTINE,NaN

In [3]:
#csv for all the parameters indexing ids
chart_items = pd.read_csv('d_items.csv')
chart_items.head()

,itemid,label,abbreviation,linksto,category,unitname,param_type,lownormalvalue,highnormalvalue
0,226228,Gender,Gender,chartevents,ADT,NaN,Text,NaN,NaN
1,226545,Race,Race,chartevents,ADT,NaN,Text,NaN,NaN
2,229877,Suction events (CH),Suction events (CH),chartevents,ECMO,NaN,Text,NaN,NaN
3,229875,Oxygenator visible (CH),Oxygenator visible (CH),chartevents,ECMO,NaN,Text,NaN,NaN
4,229266,Cannula sites visually inspected (ECMO),Cannula sites visually inspected (ECMO),chartevents,ECMO,NaN,Text,NaN,NaN

In [4]:
#to create a a dictionary
print(chart_items[chart_items['label'].str.contains('heart rate', case=False, na=False)])
print("-------------------------------")
print(chart_items[chart_items['label'].str.contains('respiratory rate', case=False, na=False)])
print("-------------------------------")
print(chart_items[chart_items['label'].str.contains('systolic', case=False, na=False)])
print("-------------------------------")
print(chart_items[chart_items['label'].str.contains('temperature', case=False, na=False)])
print("-------------------------------")
print(chart_items[chart_items['label'].str.contains('diastolic', case=False, na=False)])
print("-------------------------------")
print(chart_items[chart_items['label'].str.contains('oxygen', case=False, na=False)])

      itemid                    label     abbreviation      linksto  \
2054  220047   Heart Rate Alarm - Low   HR Alarm - Low  chartevents
2063  220046  Heart rate Alarm - High  HR Alarm - High  chartevents
2577  220045               Heart Rate               HR  chartevents

                 category unitname param_type  lownormalvalue  highnormalvalue
2054               Alarms      bpm    Numeric             NaN              NaN
2063               Alarms      bpm    Numeric             NaN              NaN
2577  Routine Vital Signs      bpm    Numeric             NaN              NaN
-------------------------------
      itemid                           label                    abbreviation  \
2284  224688          Respiratory Rate (Set)          Respiratory Rate (Set)
2314  224690        Respiratory Rate (Total)        Respiratory Rate (Total)
2329  220210                Respiratory Rate                              RR
2344  224689  Respiratory Rate (spontaneous)  Respiratory Rate (spontaneous)

          linksto     category  unitname param_type  lownormalvalue  \
2284  chartevents  Respiratory  insp/min    Numeric             NaN
2314  chartevents  Respiratory  insp/min    Numeric             NaN
2329  chartevents  Respiratory  insp/min    Numeric             NaN
2344  chartevents  Respiratory  insp/min    Numeric             NaN

      highnormalvalue
2284              NaN
2314             36.0
2329              NaN
2344              NaN
-------------------------------
      itemid                                         label  \
2167  229669  Pulmonary Atrtery Pressure Signal - Systolic
2177  229899   Left Ventricular Pressure Signal - Systolic
2186  228152             Aortic Pressure Signal - Systolic
2370  220059            Pulmonary Artery Pressure systolic
2454  226852                 PA systolic pressure(PA Line)
2462  226850                 RV systolic pressure(PA Line)
2563  225309                               ART BP Systolic
2571  227243          Manual Blood Pressure Systolic Right
2584  220179          Non Invasive Blood Pressure systolic
2586  220050              Arterial Blood Pressure systolic
2591  224167           Manual Blood Pressure Systolic Left

                                     abbreviation      linksto  \
2167  Pulmonary Artery Pressure Signal - Systolic  chartevents
2177  Left Ventricular Pressure Signal - Systolic  chartevents
2186            Aortic Pressure Signal - Systolic  chartevents
2370                                         PAPs  chartevents
2454                PA systolic pressure(PA Line)  chartevents
2462                RV systolic pressure(PA Line)  chartevents
2563                              ART BP Systolic  chartevents
2571                                 Manual BPs R  chartevents
2584                                         NBPs  chartevents
2586                                         ABPs  chartevents
2591                                 Manual BPs L  chartevents

                 category unitname param_type  lownormalvalue  highnormalvalue
2167              Impella    mmHg.    Numeric             NaN              NaN
2177              Impella     mmHg    Numeric             NaN              NaN
2186              Impella    mmHg.    Numeric             NaN              NaN
2370         Hemodynamics     mmHg    Numeric            15.0             25.0
2454    PA Line Insertion     mmHg    Numeric             NaN              NaN
2462    PA Line Insertion     mmHg    Numeric             NaN              NaN
2563  Routine Vital Signs     mmHg    Numeric             NaN              NaN
2571  Routine Vital Signs     mmHg    Numeric             NaN              NaN
2584  Routine Vital Signs     mmHg    Numeric             NaN              NaN
2586  Routine Vital Signs     mmHg    Numeric            90.0            140.0
2591  Routine Vital Signs     mmHg    Numeric             NaN              NaN
-------------------------------
      itemid                        label                 abbreviation  \
415   224674       Changes in Temperature       Changes in Temperature
1177  224027             Skin Temperature                    Skin Temp
1564  224642             Temperature Site                    Temp Site
1957  228242  Pt. Temperature (BG) (SOFT)  Pt. Temperature (BG) (SOFT)
2397  229236     Cerebral Temperature (C)               Cerebral T (C)
2570  223761       Temperature Fahrenheit                Temperature F
2573  223762          Temperature Celsius                Temperature C
2578  226329    Blood Temperature CCO (C)           Blood Temp CCO (C)
2633  227054        TemperatureF_ApacheIV        TemperatureF_ApacheIV

          linksto                category unitname param_type  lownormalvalue  \
415   chartevents              Toxicology      NaN       Text             NaN
1177  chartevents       Skin - Assessment      NaN       Text             NaN
1564  chartevents     Routine Vital Signs      NaN       Text             NaN
1957  chartevents                    Labs      NaN    Numeric             NaN
2397  chartevents            Hemodynamics       °C    Numeric             NaN
2570  chartevents     Routine Vital Signs       °F    Numeric             NaN
2573  chartevents     Routine Vital Signs       °C    Numeric             NaN
2578  chartevents     Routine Vital Signs       °C    Numeric             NaN
2633  chartevents  Scores - APACHE IV (2)       °F    Numeric             NaN

      highnormalvalue
415               NaN
1177              NaN
1564              NaN
1957              NaN
2397              NaN
2570              NaN
2573              NaN
2578              NaN
2633              NaN
-------------------------------
      itemid                                         label  \
2179  229668  Pulmonary Artery Pressure Signal - Diastolic
2180  228151            Aortic Pressure Signal - Diastolic
2184  229900  Left Ventricular Pressure Signal - Diastolic
2380  220060           Pulmonary Artery Pressure diastolic
2448  226851                RV diastolic pressure(PA Line)
2460  226853                PA diastolic pressure(PA Line)
2568  227242         Manual Blood Pressure Diastolic Right
2569  220180         Non Invasive Blood Pressure diastolic
2572  220051             Arterial Blood Pressure diastolic
2580  225310                              ART BP Diastolic
2583  224643          Manual Blood Pressure Diastolic Left

                                      abbreviation      linksto  \
2179  Pulmonary Artery Pressure Signal - Diastolic  chartevents
2180            Aortic Pressure Signal - Diastolic  chartevents
2184  Left Ventricular Pressure Signal - Diastolic  chartevents
2380                                          PAPd  chartevents
2448                RV diastolic pressure(PA Line)  chartevents
2460                PA diastolic pressure(PA Line)  chartevents
2568                                  Manual BPd R  chartevents
2569                                          NBPd  chartevents
2572                                          ABPd  chartevents
2580                              ART BP Diastolic  chartevents
2583                                  Manual BPd L  chartevents

                 category unitname param_type  lownormalvalue  highnormalvalue
2179              Impella    mmHg.    Numeric             NaN              NaN
2180              Impella    mmHg.    Numeric             NaN              NaN
2184              Impella     mmHg    Numeric             NaN              NaN
2380         Hemodynamics     mmHg    Numeric             8.0             15.0
2448    PA Line Insertion     mmHg    Numeric             NaN              NaN
2460    PA Line Insertion     mmHg    Numeric             NaN              NaN
2568  Routine Vital Signs     mmHg    Numeric             NaN              NaN
2569  Routine Vital Signs     mmHg    Numeric             NaN              NaN
2572  Routine Vital Signs     mmHg    Numeric            60.0             90.0
2580  Routine Vital Signs     mmHg    Numeric             NaN              NaN
2583  Routine Vital Signs     mmHg    Numeric             NaN              NaN
-------------------------------
      itemid                         label                  abbreviation  \
3     229875       Oxygenator visible (CH)       Oxygenator visible (CH)
9     229274     Oxygenator visible (ECMO)     Oxygenator visible (ECMO)
360   229786   Preoxygenation (Intubation)   Preoxygenation (Intubation)
1567  228232         PAR-Oxygen saturation         PAR-Oxygen saturation
2371  229235      Brain Tissue Oxygenation                         PbtO2
2408  228192         Oxygenator Sweep Rate         Oxygenator Sweep Rate
2557  226767           OxygenApacheIIScore           OxygenApacheIIScore
2631  227035          OxygenScore_ApacheIV          OxygenScore_ApacheIV
2687  225302  Pre-Oxygentated (Intubation)  Pre-Oxygentated (Intubation)
2748  228193               Oxygenator/ECMO               Oxygenator/ECMO

          linksto                category unitname param_type  lownormalvalue  \
3     chartevents                    ECMO      NaN       Text             NaN
9     chartevents                    ECMO      NaN       Text             NaN
360   chartevents              Intubation      NaN       Text             NaN
1567  chartevents     Routine Vital Signs      NaN       Text             NaN
2371  chartevents            Hemodynamics     mmHg    Numeric             NaN
2408  chartevents            Tandem Heart    L/min    Numeric             NaN
2557  chartevents      Scores - APACHE II      NaN    Numeric             NaN
2631  chartevents  Scores - APACHE IV (2)      NaN    Numeric             NaN
2687  chartevents              Intubation      NaN   Checkbox             NaN
2748  chartevents            Tandem Heart      NaN   Checkbox             NaN

      highnormalvalue
3                 NaN
9                 NaN
360               NaN
1567              NaN
2371              NaN
2408              NaN
2557              NaN
2631              NaN
2687              NaN
2748              NaN

In [5]:
#so the respective item ids of the vitals can be mapped to the respective vital from the table

In [20]:
#mapping dictionary for the vitals from d_items file:
vitals_dict = {"spO2":220277,"temp(C)":223762,"heartrate":22045,"ARTsys":225309,"ARTdia":225310,"ARTmean":225312,"NBPs":220179,"NBPd":220180,"NBPm":220181,"RR":224688}
vitals=list(vitals_dict.keys())
ids=list(vitals_dict.values())
vitals_rev_dict={vitals_dict[i]:i for i in vitals_dict}
print(vitals,ids)

['spO2', 'temp(C)', 'heartrate', 'ARTsys', 'ARTdia', 'ARTmean', 'NBPs', 'NBPd', 'NBPm', 'RR'] [220277, 223762, 22045, 225309, 225310, 225312, 220179, 220180, 220181, 224688]

In [21]:
vitals = chartevents[chartevents["itemid"].isin(ids)]
vitals.head()

,subject_id,hadm_id,stay_id,caregiver_id,charttime,storetime,itemid,value,valuenum,valueuom,warning
48,10005817,20626031,32604416,6770.0,2132-12-16 00:00:00,2132-12-16 00:02:00,223762,37,37.0,°C,0.0
92,10005817,20626031,32604416,6770.0,2132-12-16 00:00:00,2132-12-16 00:02:00,220277,95,95.0,%,0.0
103,10005817,20626031,32604416,6770.0,2132-12-16 01:00:00,2132-12-16 01:04:00,223762,37,37.0,°C,0.0
104,10005817,20626031,32604416,6770.0,2132-12-16 01:00:00,2132-12-16 01:04:00,220277,96,96.0,%,0.0
118,10005817,20626031,32604416,6770.0,2132-12-16 02:00:00,2132-12-16 02:11:00,220277,95,95.0,%,0.0

In [22]:
vitals.insert(7,"vital_parameter",vitals["itemid"].map(vitals_rev_dict))
vitals.head()

,subject_id,hadm_id,stay_id,caregiver_id,charttime,storetime,itemid,vital_parameter,value,valuenum,valueuom,warning
48,10005817,20626031,32604416,6770.0,2132-12-16 00:00:00,2132-12-16 00:02:00,223762,temp(C),37,37.0,°C,0.0
92,10005817,20626031,32604416,6770.0,2132-12-16 00:00:00,2132-12-16 00:02:00,220277,spO2,95,95.0,%,0.0
103,10005817,20626031,32604416,6770.0,2132-12-16 01:00:00,2132-12-16 01:04:00,223762,temp(C),37,37.0,°C,0.0
104,10005817,20626031,32604416,6770.0,2132-12-16 01:00:00,2132-12-16 01:04:00,220277,spO2,96,96.0,%,0.0
118,10005817,20626031,32604416,6770.0,2132-12-16 02:00:00,2132-12-16 02:11:00,220277,spO2,95,95.0,%,0.0

In [24]:
wide = vitals.pivot_table(
    index=["stay_id", "charttime"], #let these values stay the same for each entry of vitals
    columns="vital_parameter", #we would like each vital as a row
    values="valuenum", #and its value obvi
    aggfunc="first" #take the mean of multiple occurrences ( which there may not be but this is jic)
).reset_index()
wide.head()

vital_parameter,stay_id,charttime,ARTdia,ARTmean,ARTsys,NBPd,NBPm,NBPs,RR,spO2,temp(C)
0,30057454,2171-11-14 10:26:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN
1,30057454,2171-11-14 10:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.0,NaN
2,30057454,2171-11-14 10:45:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,95.0,NaN
3,30057454,2171-11-14 10:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.0,NaN
4,30057454,2171-11-14 11:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.0,NaN

In [25]:
wide["SBP"] = wide["ARTsys"].combine_first(wide["NBPs"])
wide["DBP"] = wide["ARTdia"].combine_first(wide["NBPd"])
wide["MAP"] = wide["ARTmean"].combine_first(wide["NBPm"])
#combine the systolics and diastolics w their counterparts from the non innvasive part to get one BP value

In [29]:
wide.head()

vital_parameter,stay_id,charttime,ARTdia,ARTmean,ARTsys,NBPd,NBPm,NBPs,RR,spO2,temp(C),SBP,DBP,MAP
0,30057454,2171-11-14 10:26:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN
1,30057454,2171-11-14 10:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.0,NaN,NaN,NaN,NaN
2,30057454,2171-11-14 10:45:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,95.0,NaN,NaN,NaN,NaN
3,30057454,2171-11-14 10:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.0,NaN,NaN,NaN,NaN
4,30057454,2171-11-14 11:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.0,NaN,NaN,NaN,NaN

In [30]:
vitals["vital_parameter"].value_counts()
#just so happens that oxygen values are more poulated so its ok

vital_parameter
spO2       13540
NBPd        8349
NBPs        8347
NBPm        8342
RR           801
ARTmean      488
ARTdia       486
ARTsys       486
temp(C)      391
Name: count, dtype: int64

In [31]:
vitals["itemid"].unique()

array([223762, 220277, 220181, 220179, 220180, 224688, 225312, 225310,
       225309], dtype=int64)